import { loadPushSubscriptionSnapshot, preparePushSubscriptionSnapshot, PushSubscriptionBoundaryError, type StoredPushSubscriptionData } from '@/lib/api/web-push';
import { getJSTDateString } from '@/lib/date-utils';
import { supabaseAdmin } from '@/lib/supabase';
const BATCH_SIZE = 20; const MAX_COINS = 1_000; const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; const DATE = /^\d{4}-\d{2}-\d{2}$/;
export type WeeklyFailure = 'subscriptions-query' | 'subscriptions-data' | 'subscriptions-limit' | 'subscriptions-user-limit' | 'users-query' | 'users-data' | 'user-context' | 'steps-query' | 'steps-data' | 'coins-query' | 'coins-data' | 'coins-limit' | 'push' | 'delivery-data' | 'metrics-overflow' | 'unexpected'; export interface PreviousJSTWeekRange { weekStart: string; weekEnd: string; startUtc: string; endUtcExclusive: string } export interface UserContext { locale: import('@/lib/services/push-messages').PushLocale; username: string } export interface WeeklySummary { totalSteps: number; totalCoins: number; bestDay: { date: string; steps: number } | null } export interface PreparedSubscriptions { byUser: Map<string, StoredPushSubscriptionData[]>; userIds: string[]; failures: Map<string, WeeklyFailure> }
export class WeeklySummaryFailure extends Error { constructor(readonly category: WeeklyFailure) { super('Weekly summary processing failed'); this.name = 'WeeklySummaryFailure'; } } export function failWeekly(category: WeeklyFailure): never { throw new WeeklySummaryFailure(category); } export function weeklyFailureCategory(error: unknown): WeeklyFailure { return error instanceof WeeklySummaryFailure ? error.category : 'unexpected'; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null; } function safeInteger(value: unknown): value is number { return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0; } export function addWeeklyMetric(left: number, right: number): number { const total = left + right; if (!Number.isSafeInteger(total) || total < 0) failWeekly('metrics-overflow'); return total; } export function parseWeeklyDelivery(data: unknown, count: number): { sent: number; failed: number; deduplicated: number } { if (!record(data) || !safeInteger(data.sent) || !safeInteger(data.failed) || !safeInteger(data.expired) || !safeInteger(data.skippedDuplicates) || data.expired > data.failed || data.skippedDuplicates > count || addWeeklyMetric(data.sent, data.failed) !== count - data.skippedDuplicates) failWeekly('delivery-data'); return { sent: data.sent, failed: data.failed, deduplicated: data.skippedDuplicates }; }
export function isCalendarDate(value: unknown): value is string { if (typeof value !== 'string' || !DATE.test(value)) return false; const date = new Date(`${value}T00:00:00Z`); return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value; }
export function getPreviousWeekRange(date: Date = new Date()): PreviousJSTWeekRange { const today = new Date(`${getJSTDateString(date)}T00:00:00Z`); const daysSinceMonday = (today.getUTCDay() + 6) % 7; const prevMonday = new Date(today); prevMonday.setUTCDate(today.getUTCDate() - daysSinceMonday - 7); const prevSunday = new Date(prevMonday); prevSunday.setUTCDate(prevMonday.getUTCDate() + 6); const nextMonday = new Date(prevMonday); nextMonday.setUTCDate(prevMonday.getUTCDate() + 7); const weekStart = prevMonday.toISOString().slice(0, 10); const weekEnd = prevSunday.toISOString().slice(0, 10); const nextWeekStart = nextMonday.toISOString().slice(0, 10); return { weekStart, weekEnd, startUtc: new Date(`${weekStart}T00:00:00+09:00`).toISOString(), endUtcExclusive: new Date(`${nextWeekStart}T00:00:00+09:00`).toISOString() }; }
function mapPushBoundary(error: unknown): never { if (error instanceof PushSubscriptionBoundaryError) failWeekly(error.reason === 'query' ? 'subscriptions-query' : error.reason === 'limit' ? 'subscriptions-limit' : 'subscriptions-data'); throw error; }
export async function loadWeeklySubscriptionRows(snapshot: string): Promise<unknown[]> { try { return await loadPushSubscriptionSnapshot(snapshot); } catch (error) { mapPushBoundary(error); } }
export async function prepareWeeklySubscriptions(rows: unknown[], snapshot: string): Promise<PreparedSubscriptions> { let prepared; try { prepared = await preparePushSubscriptionSnapshot(rows, snapshot); } catch (error) { mapPushBoundary(error); } const failures = new Map<string, WeeklyFailure>(); for (const id of prepared.invalidUserIds) failures.set(id, 'subscriptions-data'); for (const id of prepared.cappedUserIds) failures.set(id, 'subscriptions-user-limit'); return { byUser: prepared.byUser, userIds: prepared.userIds, failures }; }
export async function loadWeeklyUserContexts(userIds: string[]): Promise<Map<string, UserContext | null>> {
    const contexts = new Map<string, UserContext | null>(); for (let index = 0; index < userIds.length; index += BATCH_SIZE) {
        const batch = userIds.slice(index, index + BATCH_SIZE); const result = await supabaseAdmin.from('users').select('id, language, username').in('id', batch); if (result.error || !Array.isArray(result.data)) failWeekly('users-query'); for (const row of result.data) { if (!record(row) || typeof row.id !== 'string' || !UUID.test(row.id) || !batch.includes(row.id) || contexts.has(row.id)) failWeekly('users-data'); const locale = row.language; const username = row.username; contexts.set(row.id, (locale === 'ja' || locale === 'en') && typeof username === 'string' && username.length > 0 && username.length <= 64 ? { locale, username } : null); }
    } return contexts; }
export async function loadUserWeeklySummary(userId: string, range: PreviousJSTWeekRange, snapshot: string): Promise<WeeklySummary> {
    const [stepsResult, coinsResult] = await Promise.allSettled([supabaseAdmin.from('daily_steps').select('date, steps').eq('user_id', userId).gte('date', range.weekStart).lte('date', range.weekEnd).order('date', { ascending: true }), supabaseAdmin.from('coin_transactions').select('id, amount', { count: 'exact' }).eq('user_id', userId).gte('created_at', range.startUtc).lt('created_at', range.endUtcExclusive).lte('created_at', snapshot).gt('amount', 0).limit(MAX_COINS)]);
    if (stepsResult.status === 'rejected' || stepsResult.value.error) failWeekly('steps-query'); if (coinsResult.status === 'rejected' || coinsResult.value.error) failWeekly('coins-query');
    const steps = stepsResult.value.data; if (!Array.isArray(steps)) failWeekly('steps-data'); const dates = new Set<string>();
    const totalSteps = steps.reduce((sum, row) => { if (!record(row) || !isCalendarDate(row.date) || dates.has(row.date) || row.date < range.weekStart || row.date > range.weekEnd || !safeInteger(row.steps)) failWeekly('steps-data'); dates.add(row.date); return addWeeklyMetric(sum, row.steps); }, 0);
    let bestDay: WeeklySummary['bestDay'] = null; for (const row of steps) if (!bestDay || row.steps > bestDay.steps) bestDay = { date: row.date, steps: row.steps };
    const coins = coinsResult.value.data; if (!Array.isArray(coins)) failWeekly('coins-data'); if (!safeInteger(coinsResult.value.count) || coinsResult.value.count !== coins.length) failWeekly('coins-limit'); const ids = new Set<string>();
    const totalCoins = coins.reduce((sum, row) => { if (!record(row) || typeof row.id !== 'string' || !UUID.test(row.id) || ids.has(row.id) || !safeInteger(row.amount) || row.amount === 0) failWeekly('coins-data'); ids.add(row.id); return addWeeklyMetric(sum, row.amount); }, 0);
    return { totalSteps, totalCoins, bestDay }; }
