import { isAllowedPushEndpoint, isValidPushKey, MAX_PUSH_SUBSCRIPTIONS, type StoredPushSubscriptionData } from '@/lib/api/web-push';
import { AppError, reportError } from '@/lib/errors';
import { supabaseAdmin } from '@/lib/supabase';
const BATCH_SIZE = 20; const PAGE_SIZE = 900; const MAX_SUBSCRIPTIONS = 10_000; const MAX_COINS = 1_000; const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; const DATE = /^\d{4}-\d{2}-\d{2}$/;
export type WeeklyFailure = 'subscriptions-query' | 'subscriptions-data' | 'subscriptions-limit' | 'subscriptions-user-limit' | 'users-query' | 'users-data' | 'user-context' | 'steps-query' | 'steps-data' | 'coins-query' | 'coins-data' | 'coins-limit' | 'push' | 'delivery-data' | 'metrics-overflow' | 'unexpected'; export interface PreviousJSTWeekRange { weekStart: string; weekEnd: string; startUtc: string; endUtcExclusive: string } export interface UserContext { locale: import('@/lib/services/push-messages').PushLocale; username: string } export interface WeeklySummary { totalSteps: number; totalCoins: number; bestDay: { date: string; steps: number } | null } export interface PreparedSubscriptions { byUser: Map<string, StoredPushSubscriptionData[]>; userIds: string[]; failures: Map<string, WeeklyFailure>; cleanupIds: Map<string, string[]> }
export class WeeklySummaryFailure extends Error { constructor(readonly category: WeeklyFailure) { super('Weekly summary processing failed'); this.name = 'WeeklySummaryFailure'; } } export function failWeekly(category: WeeklyFailure): never { throw new WeeklySummaryFailure(category); } export function weeklyFailureCategory(error: unknown): WeeklyFailure { return error instanceof WeeklySummaryFailure ? error.category : 'unexpected'; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null; } function safeInteger(value: unknown): value is number { return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0; } export function addWeeklyMetric(left: number, right: number): number { const total = left + right; if (!Number.isSafeInteger(total) || total < 0) failWeekly('metrics-overflow'); return total; } export function parseWeeklyDelivery(data: unknown, count: number): { sent: number; failed: number; deduplicated: number } { if (!record(data) || !safeInteger(data.sent) || !safeInteger(data.failed) || !safeInteger(data.expired) || !safeInteger(data.skippedDuplicates) || data.expired > data.failed || data.skippedDuplicates > count || addWeeklyMetric(data.sent, data.failed) !== count - data.skippedDuplicates) failWeekly('delivery-data'); return { sent: data.sent, failed: data.failed, deduplicated: data.skippedDuplicates }; }
export async function loadWeeklySubscriptionRows(snapshot: string): Promise<unknown[]> { const rows: unknown[] = []; let cursor: string | null = null; while (true) { const limit = Math.min(PAGE_SIZE, MAX_SUBSCRIPTIONS - rows.length + 1); let query = supabaseAdmin.from('push_subscriptions').select('id, user_id, endpoint, p256dh, auth, user_agent, created_at').or(`created_at.lte.${snapshot},created_at.is.null`).order('id', { ascending: true }).limit(limit); if (cursor) query = query.gt('id', cursor); const page = await query; if (page.error) failWeekly('subscriptions-query'); if (!Array.isArray(page.data)) failWeekly('subscriptions-data'); rows.push(...page.data); if (rows.length > MAX_SUBSCRIPTIONS) failWeekly('subscriptions-limit'); if (page.data.length < limit) return rows; const last = page.data.at(-1); if (!record(last) || typeof last.id !== 'string' || (cursor !== null && last.id <= cursor)) failWeekly('subscriptions-data'); cursor = last.id; } }
export function prepareWeeklySubscriptions(rows: unknown[], snapshot: string): PreparedSubscriptions { const byUser = new Map<string, StoredPushSubscriptionData[]>(); const userIds = new Set<string>(); const failures = new Map<string, WeeklyFailure>(); const cleanupIds = new Map<string, string[]>(); const rowIds = new Set<string>(); const snapshotMs = Date.parse(snapshot);
    for (const row of rows) { if (!record(row) || typeof row.id !== 'string' || !UUID.test(row.id) || typeof row.user_id !== 'string' || !UUID.test(row.user_id) || rowIds.has(row.id)) failWeekly('subscriptions-data'); rowIds.add(row.id); userIds.add(row.user_id); if (!isAllowedPushEndpoint(row.endpoint) || !isValidPushKey(row.p256dh, 256, 65) || !isValidPushKey(row.auth, 128, 16) || (row.user_agent !== null && typeof row.user_agent !== 'string') || typeof row.created_at !== 'string' || !Number.isFinite(Date.parse(row.created_at)) || Date.parse(row.created_at) > snapshotMs) { failures.set(row.user_id, 'subscriptions-data'); cleanupIds.set(row.user_id, [...(cleanupIds.get(row.user_id) ?? []), row.id]); continue; } const subs = byUser.get(row.user_id) ?? []; subs.push({ id: row.id, endpoint: row.endpoint, p256dh: row.p256dh, auth: row.auth, user_agent: row.user_agent, created_at: row.created_at }); byUser.set(row.user_id, subs); }
    for (const [userId, subs] of byUser) if (subs.length > MAX_PUSH_SUBSCRIPTIONS) failures.set(userId, 'subscriptions-user-limit'); for (const userId of failures.keys()) byUser.delete(userId); return { byUser, userIds: Array.from(userIds), failures, cleanupIds }; }
export async function cleanupInvalidWeeklySubscriptions(cleanupIds: Map<string, string[]>, snapshot: string): Promise<void> {
    let cleanupIndex = 0; for (const [userId, ids] of cleanupIds) { let failed = false; try { const result = await supabaseAdmin.from('push_subscriptions').delete().eq('user_id', userId).in('id', ids).or(`created_at.lte.${snapshot},created_at.is.null`); failed = Boolean(result.error); } catch { failed = true; } if (failed) reportError('cron/weekly-summary:cleanup', new AppError('Weekly summary processing failed', 'WEEKLY_SUMMARY_FAILURE', { category: 'subscriptions-cleanup', cleanupIndex, count: ids.length })); cleanupIndex++; } }
export async function loadWeeklyUserContexts(userIds: string[]): Promise<Map<string, UserContext | null>> {
    const contexts = new Map<string, UserContext | null>(); for (let index = 0; index < userIds.length; index += BATCH_SIZE) {
        const batch = userIds.slice(index, index + BATCH_SIZE); const result = await supabaseAdmin.from('users').select('id, language, username').in('id', batch); if (result.error || !Array.isArray(result.data)) failWeekly('users-query'); for (const row of result.data) { if (!record(row) || typeof row.id !== 'string' || !UUID.test(row.id) || !batch.includes(row.id) || contexts.has(row.id)) failWeekly('users-data'); const locale = row.language; const username = row.username; contexts.set(row.id, (locale === 'ja' || locale === 'en') && typeof username === 'string' && username.length > 0 && username.length <= 64 ? { locale, username } : null); }
    } return contexts; }
export async function loadUserWeeklySummary(userId: string, range: PreviousJSTWeekRange, snapshot: string): Promise<WeeklySummary> {
    const [stepsResult, coinsResult] = await Promise.allSettled([supabaseAdmin.from('daily_steps').select('date, steps').eq('user_id', userId).gte('date', range.weekStart).lte('date', range.weekEnd).order('date', { ascending: true }), supabaseAdmin.from('coin_transactions').select('id, amount', { count: 'exact' }).eq('user_id', userId).gte('created_at', range.startUtc).lt('created_at', range.endUtcExclusive).lte('created_at', snapshot).gt('amount', 0).limit(MAX_COINS)]);
    if (stepsResult.status === 'rejected' || stepsResult.value.error) failWeekly('steps-query'); if (coinsResult.status === 'rejected' || coinsResult.value.error) failWeekly('coins-query');
    const steps = stepsResult.value.data; if (!Array.isArray(steps)) failWeekly('steps-data'); const dates = new Set<string>();
    const totalSteps = steps.reduce((sum, row) => { if (!record(row) || typeof row.date !== 'string' || !DATE.test(row.date) || !Number.isFinite(Date.parse(`${row.date}T00:00:00Z`)) || dates.has(row.date) || row.date < range.weekStart || row.date > range.weekEnd || !safeInteger(row.steps)) failWeekly('steps-data'); dates.add(row.date); return addWeeklyMetric(sum, row.steps); }, 0);
    let bestDay: WeeklySummary['bestDay'] = null; for (const row of steps) if (!bestDay || row.steps > bestDay.steps) bestDay = { date: row.date, steps: row.steps };
    const coins = coinsResult.value.data; if (!Array.isArray(coins)) failWeekly('coins-data'); if (!safeInteger(coinsResult.value.count) || coinsResult.value.count !== coins.length) failWeekly('coins-limit'); const ids = new Set<string>();
    const totalCoins = coins.reduce((sum, row) => { if (!record(row) || typeof row.id !== 'string' || !UUID.test(row.id) || ids.has(row.id) || !safeInteger(row.amount) || row.amount === 0) failWeekly('coins-data'); ids.add(row.id); return addWeeklyMetric(sum, row.amount); }, 0);
    return { totalSteps, totalCoins, bestDay }; }
