import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
const mocks = vi.hoisted(() => ({ from: vi.fn(), reportError: vi.fn(), send: vi.fn() }));
vi.mock('@/lib/api/web-push', async () => ({ ...await vi.importActual<typeof import('@/lib/api/web-push')>('@/lib/api/web-push'), sendWebPushNotifications: mocks.send }));
vi.mock('@/lib/errors', async () => ({ ...await vi.importActual<typeof import('@/lib/errors')>('@/lib/errors'), reportError: mocks.reportError }));
vi.mock('@/lib/supabase', () => ({ supabaseAdmin: { from: mocks.from } }));
import { GET } from './route';
import { getPreviousWeekRange, isCalendarDate } from '@/lib/services/weekly-summary';
const ORIGINAL_SECRET = process.env.CRON_SECRET; const SECRET = 'cron-secret';
const IDS = Array.from({ length: 902 }, (_, index) => `00000000-0000-4000-8000-${String(index + 1).padStart(12, '0')}`);
interface Result { data: unknown; error: unknown; count?: unknown } interface Call { table: string; method: string; args: unknown[] }
type QueryMethod = 'select' | 'in' | 'is' | 'eq' | 'gte' | 'lte' | 'lt' | 'gt' | 'or' | 'order' | 'limit'; type Query = PromiseLike<Result> & Record<QueryMethod, (...args: unknown[]) => Query>;
let tableResults: Record<string, Result>; let summaries: Map<string, { steps: Result; coins: Result }>; let calls: Call[];
const subscription = (index: number, userId = IDS[index]): Record<string, unknown> => ({ id: `10000000-0000-4000-8000-${String(index + 1).padStart(12, '0')}`, user_id: userId, endpoint: `https://fcm.googleapis.com/fcm/send/${index}`, p256dh: 'BGsX0fLhLEJH-Lzm5WOkQPJ3A32BLeszoPShOUXYmMKWT-NC4v4af5uO5-tKfA-eFivOM1drMV7Oy7ZAaDe_UfU', auth: 'A'.repeat(22), user_agent: 'Browser', created_at: '2026-07-01T00:00:00Z' });
const coin = (index: number, amount = 5): Record<string, unknown> => ({ id: `20000000-0000-4000-8000-${String(index + 1).padStart(12, '0')}`, amount });
function setUsers(count: number): void { const ids = IDS.slice(0, count); tableResults.push_subscriptions = { data: ids.map((id, index) => subscription(index, id)), error: null }; tableResults.users = { data: ids.map((id, index) => ({ id, language: index % 2 ? 'en' : 'ja', username: `user${index}` })), error: null }; summaries = new Map(ids.map((id) => [id, { steps: { data: [], error: null }, coins: { data: [], error: null } }])); }
function resolveResult(table: string, userId: string, limit: number, requested: string[] | null, exactCount: boolean): Result { const result = (table === 'daily_steps' ? summaries.get(userId)?.steps : table === 'coin_transactions' ? summaries.get(userId)?.coins : tableResults[table]) ?? { data: null, error: { code: 'missing-mock' } }; if (!Array.isArray(result.data)) return result; if (table === 'push_subscriptions') { const data = result.data.slice(0, limit); return { ...result, data, count: exactCount ? ('count' in result ? result.count : result.data.length) : result.count }; } if (table === 'users' && requested) return { ...result, data: result.data.filter((row) => typeof row === 'object' && row !== null && requested.includes(String(Reflect.get(row, 'id')))) }; return table === 'coin_transactions' ? { ...result, count: 'count' in result ? result.count : result.data.length } : result; }
function createQuery(table: string): Query { let userId = ''; let limit = Number.POSITIVE_INFINITY; let requested: string[] | null = null; let exactCount = false; const record = (method: string, args: unknown[]): Query => { calls.push({ table, method, args }); if (method === 'select' && typeof args[1] === 'object' && args[1] !== null && Reflect.get(args[1], 'count') === 'exact') exactCount = true; if (method === 'eq' && args[0] === 'user_id') userId = String(args[1]); if (method === 'limit') limit = Number(args[0]); if (method === 'in' && args[0] === 'id' && Array.isArray(args[1])) requested = args[1].filter((value): value is string => typeof value === 'string'); return query; }; const methods = ['select', 'in', 'is', 'eq', 'gte', 'lte', 'lt', 'gt', 'or', 'order', 'limit'] as const; const fluentMethods = Object.fromEntries(methods.map((method) => [method, (...args: unknown[]) => record(method, args)])) as Record<QueryMethod, (...args: unknown[]) => Query>; const query: Query = { ...fluentMethods, then: (resolve, reject) => Promise.resolve(resolveResult(table, userId, limit, requested, exactCount)).then(resolve, reject) }; return query; }
function request(secret = SECRET): Request { return new Request('http://localhost/api/cron/weekly-summary', { headers: { authorization: 'Bearer ' + secret } }); }
function expectFixedReports(privateValues: string[] = []): void { for (const [operation, error] of mocks.reportError.mock.calls) { expect(operation).toMatch(/^cron\/weekly-summary/); expect(error).toBeInstanceOf(Error); if (!(error instanceof Error)) continue; expect(error.message).toBe('Weekly summary processing failed'); expect(Reflect.get(error, 'cause')).toBeUndefined(); const context = Reflect.get(error, 'context'); expect(context).toEqual(expect.objectContaining({ category: expect.any(String) })); expect(Object.keys(context).every((key) => ['category', 'batchIndex', 'itemIndex', 'cleanupIndex', 'count'].includes(key))).toBe(true); expect(Object.values(context).every((value) => typeof value === 'string' || typeof value === 'number')).toBe(true); for (const value of privateValues) { expect(operation).not.toContain(value); expect(error.message).not.toContain(value); expect(Object.values(context)).not.toContain(value); } } }
beforeEach(() => { vi.clearAllMocks(); vi.useFakeTimers(); vi.setSystemTime(new Date('2026-07-13T00:00:00Z')); process.env.CRON_SECRET = SECRET; tableResults = {}; calls = []; setUsers(2); mocks.from.mockImplementation((table: string) => createQuery(table)); mocks.send.mockResolvedValue({ sent: 1, failed: 0, expired: 0, skippedDuplicates: 0 }); });
afterAll(() => { vi.useRealTimers(); if (ORIGINAL_SECRET === undefined) delete process.env.CRON_SECRET; else process.env.CRON_SECRET = ORIGINAL_SECRET; });
describe('getPreviousWeekRange', () => { it.each([['JST元日', '2025-12-31T15:00:00Z', ['2025-12-22', '2025-12-28', '2025-12-21T15:00:00.000Z', '2025-12-28T15:00:00.000Z']], ['月跨ぎ', '2026-03-01T15:00:00Z', ['2026-02-23', '2026-03-01', '2026-02-22T15:00:00.000Z', '2026-03-01T15:00:00.000Z']], ['DSTなしの夏季', '2026-07-13T00:00:00Z', ['2026-07-06', '2026-07-12', '2026-07-05T15:00:00.000Z', '2026-07-12T15:00:00.000Z']]])('%sでもJST月曜00時のUTC半開区間を返す', (_name, input, expected) => expect(Object.values(getPreviousWeekRange(new Date(input)))).toEqual(expected)); });
describe('isCalendarDate', () => { it.each([['leap day', '2024-02-29', true], ['month end', '2026-04-30', true], ['year boundary', '2025-01-01', true], ['normalized invalid', '2026-02-30', false], ['invalid month', '2026-99-99', false], ['zero month', '2026-00-00', false]])('%sを厳格判定する', (_name, input, expected) => expect(isCalendarDate(input)).toBe(expected)); });
describe('GET /api/cron/weekly-summary', () => {
    it.each([[undefined, SECRET], [SECRET, 'wrong']])('認証失敗の場合、DB前に401を返す', async (configured, supplied) => { if (configured === undefined) delete process.env.CRON_SECRET; const response = await GET(request(supplied)); expect(response.status).toBe(401); expect(mocks.from).not.toHaveBeenCalled(); });
    it('全成功の場合、JST前週を照会してja/en各1通とdedup集計を返す', async () => {
        tableResults.push_subscriptions.data = [subscription(0), subscription(2, IDS[0]), { ...subscription(1), created_at: '2026-07-13T00:00:01Z' }]; summaries.get(IDS[0])!.steps.data = [{ date: '2026-07-06', steps: 0 }]; summaries.get(IDS[0])!.coins.data = Array.from({ length: 1000 }, (_, index) => coin(index));
        mocks.send.mockResolvedValueOnce({ sent: 1, failed: 0, expired: 0, skippedDuplicates: 1 }).mockResolvedValueOnce({ sent: 1, failed: 0, expired: 0, skippedDuplicates: 0 });
        const response = await GET(request()); expect(response.status).toBe(200); expect(await response.json()).toMatchObject({ success: true, weekRange: '2026-07-06 ~ 2026-07-12', users: 2, sent: 2, failed: 0, deduplicated: 1 });
        expect(mocks.send.mock.calls.map((call) => call[2])).toEqual([expect.objectContaining({ title: '📊 ウィークリーサマリー', body: expect.stringContaining('ベスト: 月 (0 歩)'), url: '/user/user0', locale: 'ja', tag: 'weekly-summary' }), expect.objectContaining({ title: '📊 Weekly Summary', body: 'Last week: 0 steps | +0 UC', url: '/user/user1', locale: 'en', tag: 'weekly-summary' })]); expect(calls).toEqual(expect.arrayContaining([{ table: 'push_subscriptions', method: 'select', args: ['id, user_id, endpoint, p256dh, auth, user_agent, created_at', { count: 'exact' }] }, { table: 'push_subscriptions', method: 'order', args: ['id', { ascending: true }] }, { table: 'push_subscriptions', method: 'limit', args: [901] }, { table: 'daily_steps', method: 'gte', args: ['date', '2026-07-06'] }, { table: 'daily_steps', method: 'lte', args: ['date', '2026-07-12'] }, { table: 'coin_transactions', method: 'select', args: ['id, amount', { count: 'exact' }] }, { table: 'coin_transactions', method: 'limit', args: [1000] }, { table: 'coin_transactions', method: 'gte', args: ['created_at', '2026-07-05T15:00:00.000Z'] }, { table: 'coin_transactions', method: 'lt', args: ['created_at', '2026-07-12T15:00:00.000Z'] }, { table: 'coin_transactions', method: 'gt', args: ['amount', 0] }]));
    });
    it.each([
        ['subscriptions error', () => { tableResults.push_subscriptions.error = { message: IDS[0] }; }], ['subscriptions null', () => { tableResults.push_subscriptions.data = null; }], ['subscriptions duplicate', () => { tableResults.push_subscriptions.data = [subscription(0), subscription(0)]; }], ['subscriptions 21 duplicate', () => { tableResults.push_subscriptions.data = Array.from({ length: 21 }, () => subscription(0)); }], ['subscriptions cross-user duplicate', () => { tableResults.push_subscriptions.data = [{ ...subscription(0), auth: 'a' }, { ...subscription(0, IDS[1]), endpoint: 'https://fcm.googleapis.com/valid' }]; }], ['subscriptions identity', () => { tableResults.push_subscriptions.data = [{ ...subscription(0), user_id: 'invalid' }]; }],
        ['subscriptions total cap', () => setUsers(901)], ['users error', () => { tableResults.users.error = { message: IDS[0] }; }], ['users null', () => { tableResults.users.data = null; }],
        ['users duplicate', () => { tableResults.users.data = [{ id: IDS[0], language: 'ja', username: 'user0' }, { id: IDS[0], language: 'en', username: 'user0' }]; }],
    ])('%sの場合、送信せず固定500を返す', async (_name, configure) => { configure(); const response = await GET(request()); expect(response.status).toBe(500); expect(mocks.send).not.toHaveBeenCalled(); expect(calls.filter((call) => call.method === 'delete')).toHaveLength(0); expect(await response.json()).toEqual({ success: false, error: 'Internal Server Error' }); expectFixedReports([IDS[0]]); if (_name === 'subscriptions total cap') expect(Reflect.get(mocks.reportError.mock.calls[0]?.[1] ?? {}, 'context')).toEqual(expect.objectContaining({ category: 'subscription-snapshot-cap' })); });
    it.each([
        ['legacy endpoint', () => { tableResults.push_subscriptions.data = [{ ...subscription(0), endpoint: 'http://private' }, subscription(1)]; }], ['legacy auth', () => { tableResults.push_subscriptions.data = [{ ...subscription(0), auth: 'a' }, subscription(1)]; }], ['legacy p256', () => { tableResults.push_subscriptions.data = [{ ...subscription(0), p256dh: 'A'.repeat(87) }, subscription(1)]; }], ['legacy null created', () => { tableResults.push_subscriptions.data = [{ ...subscription(0), created_at: null }, subscription(1)]; }],
        ['invalid subscriptions user cap', () => { tableResults.push_subscriptions.data = [...Array.from({ length: 21 }, (_, index) => ({ ...subscription(index, IDS[0]), auth: 'a' })), subscription(21, IDS[1])]; }], ['valid subscriptions user cap', () => { tableResults.push_subscriptions.data = [...Array.from({ length: 21 }, (_, index) => subscription(index, IDS[0])), subscription(21, IDS[1])]; }],
        ['steps error', () => { summaries.get(IDS[0])!.steps = { data: null, error: { message: IDS[0] } }; }], ['steps null', () => { summaries.get(IDS[0])!.steps.data = null; }], ['steps invalid', () => { summaries.get(IDS[0])!.steps.data = [{ date: '2026-07-06', steps: '1' }]; }], ['steps negative', () => { summaries.get(IDS[0])!.steps.data = [{ date: '2026-07-06', steps: -1 }]; }],
        ['steps unsafe', () => { summaries.get(IDS[0])!.steps.data = [{ date: '2026-07-06', steps: Number.MAX_SAFE_INTEGER + 1 }]; }], ['steps duplicate', () => { summaries.get(IDS[0])!.steps.data = [{ date: '2026-07-06', steps: 1 }, { date: '2026-07-06', steps: 2 }]; }], ['steps overflow', () => { summaries.get(IDS[0])!.steps.data = [{ date: '2026-07-06', steps: Number.MAX_SAFE_INTEGER }, { date: '2026-07-07', steps: 1 }]; }], ['coins error', () => { summaries.get(IDS[0])!.coins = { data: null, error: { message: IDS[0] } }; }],
        ['coins null', () => { summaries.get(IDS[0])!.coins.data = null; }], ['coins count null', () => { summaries.get(IDS[0])!.coins = { data: [], error: null, count: null }; }], ['coins cutoff', () => { summaries.get(IDS[0])!.coins = { data: Array.from({ length: 1000 }, (_, index) => coin(index)), error: null, count: 1001 }; }], ['coins negative', () => { summaries.get(IDS[0])!.coins.data = [coin(0, -1)]; }], ['coins zero', () => { summaries.get(IDS[0])!.coins.data = [coin(0, 0)]; }], ['coins shape', () => { summaries.get(IDS[0])!.coins.data = [{ ...coin(0), amount: '5' }]; }],
        ['coins unsafe', () => { summaries.get(IDS[0])!.coins.data = [coin(0, Number.MAX_SAFE_INTEGER + 1)]; }], ['coins duplicate', () => { summaries.get(IDS[0])!.coins.data = [coin(0), coin(0)]; }], ['coins overflow', () => { summaries.get(IDS[0])!.coins.data = [coin(0, Number.MAX_SAFE_INTEGER), coin(1, 1)]; }], ['missing user', () => { tableResults.users.data = [{ id: IDS[1], language: 'en', username: 'user1' }]; }],
        ['invalid locale', () => { tableResults.users.data = [{ id: IDS[0], language: 'fr', username: 'user0' }, { id: IDS[1], language: 'en', username: 'user1' }]; }], ['invalid username', () => { tableResults.users.data = [{ id: IDS[0], language: 'ja', username: null }, { id: IDS[1], language: 'en', username: 'user1' }]; }],
    ])('%sを既定値へ偽装せず他ユーザーだけ送る', async (_name, configure) => { configure(); const response = await GET(request()); const body = await response.json(); expect(response.status).toBe(503); expect(mocks.send).toHaveBeenCalledTimes(1); expect(body).toMatchObject({ success: false, sent: 1, failed: 1 }); expect(mocks.send.mock.calls.every((call) => call[1].length <= 20)).toBe(true); expect(calls.filter((call) => call.method === 'delete')).toHaveLength(0); expect(Object.values(body)).not.toContain(IDS[0]); expectFixedReports([IDS[0]]); }); it('共有endpointの場合、全所有者を隔離して非PII集計で無関係userだけ送る', async () => { setUsers(3); const sharedEndpoint = 'https://fcm.googleapis.com/fcm/send/private-shared'; tableResults.push_subscriptions.data = [{ ...subscription(0, IDS[0]), endpoint: sharedEndpoint }, { ...subscription(1, IDS[1]), endpoint: sharedEndpoint }, subscription(2, IDS[2])]; const response = await GET(request()); const body = await response.json(); expect(response.status).toBe(503); expect(body).toMatchObject({ success: false, users: 3, sent: 1, failed: 2 }); expect(mocks.send).toHaveBeenCalledTimes(1); expect(mocks.send.mock.calls[0]?.[0]).toBe(IDS[2]); expect(JSON.stringify(body)).not.toContain(sharedEndpoint); expectFixedReports([IDS[0], IDS[1], sharedEndpoint]); });
    it('Push例外を固定エラーへ変換して後続送信と非PII集計を維持する', async () => {
        const raw = new Error(`${IDS[0]} https://fcm.googleapis.com/private`); mocks.send.mockRejectedValueOnce(raw).mockResolvedValueOnce({ sent: 1, failed: 0, expired: 0, skippedDuplicates: 0 });
        const response = await GET(request()); const body = await response.json(); expect(response.status).toBe(503); expect(body).toMatchObject({ sent: 1, failed: 1 }); expect(mocks.send).toHaveBeenCalledTimes(2);
        for (const call of mocks.reportError.mock.calls) expect(call[1]).not.toBe(raw); expectFixedReports([IDS[0], 'https://fcm.googleapis.com/private']);
    });
    it('単一statement上限900件を20ユーザーbatchで処理する', async () => {
        setUsers(900); let active = 0; let maxActive = 0;
        mocks.send.mockImplementation(async () => { active++; maxActive = Math.max(maxActive, active); await Promise.resolve(); active--; return { sent: 1, failed: 0, expired: 0, skippedDuplicates: 0 }; });
        const response = await GET(request()); expect(response.status).toBe(200); expect(await response.json()).toMatchObject({ users: 900 }); expect(maxActive).toBe(20); expect(mocks.from).toHaveBeenCalledTimes(1846); expect(mocks.send).toHaveBeenCalledTimes(900);
        expect(calls.filter((call) => call.table === 'push_subscriptions' && call.method === 'select')).toHaveLength(1); expect(calls.filter((call) => call.table === 'push_subscriptions' && call.method === 'limit').map((call) => call.args)).toEqual([[901]]);
        expect(calls.filter((call) => call.table === 'push_subscriptions' && ['is', 'lte', 'gt'].includes(call.method))).toHaveLength(0); expect(calls.filter((call) => call.table === 'users' && call.method === 'in')).toHaveLength(45);
    });
});
